export const ROUTES = {
  HOME: '/',
  SHOP: '/shop',
  COLLECTION: (slug: string) => `/collections/${slug}`,
  PRODUCT_DETAIL: (slugOrId: string) => `/product/${slugOrId}`,
  SEARCH: '/search',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDER_CONFIRMATION: (orderId: string) => `/order-confirmation/${orderId}`,
  WISHLIST: '/wishlist',
  ACCOUNT: '/account',
  ORDERS: '/orders',
  LOGIN: '/login',
  REGISTER: '/register',
  ABOUT: '/about',
  CONTACT: '/contact',
  FAQ: '/faq',
  SHIPPING: '/shipping-delivery',
  RETURNS: '/returns-refunds',
  PRIVACY: '/privacy-policy',
  TERMS: '/terms',
  ADMIN: '/admin',
} as const;
